(function(){
  'use strict';

  window.DASSA_AGENT_INDUSTRIES=[
    {id:'automotive',title:'Automotive',icon:'directions_car',summary:'Keep service, repair, sales, and roadside inquiries moving.',caller:'I need help with my vehicle. What is the next available service window?',response:'I can capture the vehicle, service need, preferred timing, and contact information for the right automotive team.'},
    {id:'home-field-services',title:'Home & Field Services',icon:'home_repair_service',summary:'Capture urgent service needs and organize field-team handoffs.',caller:'We need service at our property. How soon can someone follow up?',response:'I can capture the location, service need, urgency, and callback information for a clear dispatch review.'},
    {id:'healthcare-wellness',title:'Healthcare & Wellness',icon:'medical_services',summary:'Guide appointment and practice inquiries through a consistent intake path.',caller:'I would like to request an appointment and understand the next step.',response:'I can capture the appointment request and contact details so the practice team has a clear follow-up path.'},
    {id:'hospitality-retail',title:'Hospitality & Retail',icon:'storefront',summary:'Support reservations, orders, bookings, and customer questions.',caller:'I have a question about a booking or purchase and need help with the next step.',response:'I can identify the request, capture the important details, and route it for the appropriate follow-up.'},
    {id:'professional-services',title:'Professional Services',icon:'business_center',summary:'Give high-intent inquiries a clear intake and ownership path.',caller:'I am looking for professional help and would like to speak with the right person.',response:'I can capture the reason for the inquiry, contact details, and preferred follow-up for the appropriate team.'},
    {id:'industrial-logistics',title:'Industrial & Logistics',icon:'factory',summary:'Keep operational, shipping, facility, and receiving calls organized.',caller:'I am calling about an operational issue and need to reach the correct team.',response:'I can capture the location, shipment or facility details, urgency, and callback information for a clear handoff.'},
    {id:'property-government',title:'Property & Government',icon:'account_balance',summary:'Route resident, tenant, utility, and citizen-service requests clearly.',caller:'I have a property or public-service question and am not sure who handles it.',response:'I can capture the request, location, contact information, and desired outcome so it reaches the right department.'},
    {id:'education-community',title:'Education & Community',icon:'school',summary:'Help families, members, donors, and communities reach the right program.',caller:'I have a question about enrollment, a program, or an upcoming activity.',response:'I can capture the question and contact details so the correct education or community team can respond.'}
  ];

  window.DASSA_AGENT_CATALOG=[
    {id:'auto-repair',business:'Auto Repair',industry:'automotive',role:'Virtual Service Advisor',icon:'car_repair',verticalId:'auto-repair',keywords:['mechanic','mechanics','cars','car','brakes','garage','repair shop','automotive service'],cardData:{pain:'Service drive jammed at opening?',fix:'The Virtual Service Advisor captures overflow service requests and gives the shop a clear booking follow-up path.'}},
    {id:'window-tint',business:'Window Tint',industry:'automotive',role:'Virtual Scheduling Desk',icon:'directions_car',keywords:['tint','tinter','window film','car windows','ceramic tint','automotive tint'],cardData:{pain:'Hands full while the quote calls keep coming?',fix:'The Virtual Scheduling Desk captures vehicle details, tint questions, and preferred appointment times.'}},
    {id:'auto-body',business:'Auto Body',industry:'automotive',role:'Virtual Collision Coordinator',icon:'car_crash',verticalId:'auto-body',keywords:['body shop','collision','dent','paint','accident','collision repair'],cardData:{pain:'Estimate calls arriving while the team is inspecting vehicles?',fix:'The Virtual Collision Coordinator captures damage inquiries, vehicle details, and the requested next step.'}},
    {id:'dealerships',business:'Dealerships',industry:'automotive',role:'Virtual Showroom Operator',icon:'garage',keywords:['dealer','car sales','showroom','vehicles','test drive','autos'],cardData:{pain:'Sales calls competing with customers on the showroom floor?',fix:'The Virtual Showroom Operator captures vehicle interest, test-drive requests, and buyer contact information.'}},
    {id:'tire-shops',business:'Tire Shops',industry:'automotive',role:'Virtual Service Desk',icon:'tire_repair',keywords:['tires','tyres','alignment','wheel','auto service','tire store'],cardData:{pain:'The counter busy while drivers call about tires and availability?',fix:'The Virtual Service Desk captures vehicle, tire, service, and preferred appointment details.'}},
    {id:'towing',business:'Towing',industry:'automotive',role:'Virtual Dispatch Coordinator',icon:'tow',keywords:['tow','tow truck','roadside','recovery','stranded','breakdown'],cardData:{pain:'A stranded driver calling while dispatch is already coordinating trucks?',fix:'The Virtual Dispatch Coordinator captures location, vehicle, safety, and callback details for dispatch review.'}},
    {id:'auto-salvage',business:'Auto Salvage',industry:'automotive',role:'Virtual Parts & Inventory Desk',icon:'minor_crash',keywords:['junkyard','salvage yard','used parts','auto parts','wrecking yard','inventory'],cardData:{pain:'Parts inquiries interrupting yard and inventory work?',fix:'The Virtual Parts & Inventory Desk captures the vehicle, part, condition, and buyer contact details.'}},

    {id:'electrical',business:'Electrical',industry:'home-field-services',role:'Virtual Service Dispatcher',icon:'electrical_services',verticalId:'electrical',keywords:['electrician','electric','wiring','power','contractor','service call'],cardData:{pain:'Service calls arriving while electricians are in the field?',fix:'The Virtual Service Dispatcher captures the electrical issue, location, urgency, and callback information.'}},
    {id:'general-contractors',business:'General Contractors',industry:'home-field-services',role:'Virtual Project Estimating Desk',icon:'engineering',keywords:['general contractor','construction','builder','remodeling','renovation','estimate'],cardData:{pain:'Project inquiries arriving while the team is on a jobsite?',fix:'The Virtual Project Estimating Desk captures project scope, location, timing, and estimate requests.'}},
    {id:'hvac',business:'HVAC',industry:'home-field-services',role:'Virtual Service Dispatcher',icon:'mode_fan',verticalId:'hvac',keywords:['ac','air conditioning','heating','cooling','contractor','field','repair','no cool'],cardData:{pain:'Summer demand overwhelming the phones?',fix:'The Virtual Service Dispatcher captures no-cool requests, urgency, address, and callback details for dispatch.'}},
    {id:'pavers',business:'Pavers',industry:'home-field-services',role:'Virtual Estimating Coordinator',icon:'construction',keywords:['paving','driveway','patio','hardscape','stone','estimate'],cardData:{pain:'Estimate requests coming in while crews are laying pavers?',fix:'The Virtual Estimating Coordinator captures project type, measurements, location, and preferred timing.'}},
    {id:'plumbing',business:'Plumbing',industry:'home-field-services',role:'Virtual Service Dispatcher',icon:'plumbing',verticalId:'plumbing',keywords:['plumber','pipes','leak','drain','water heater','service call'],cardData:{pain:'Urgent leak calls arriving while plumbers are on jobs?',fix:'The Virtual Service Dispatcher captures the plumbing issue, urgency, location, and callback information.'}},
    {id:'pool-spa-services',business:'Pool & Spa Services',industry:'home-field-services',role:'Virtual Service Desk',icon:'pool',verticalId:'pool-spa',keywords:['pool','spa service','pool cleaning','pool repair','route','chlorine'],cardData:{pain:'Route questions and new-service calls piling up?',fix:'The Virtual Service Desk captures service needs, property details, and route follow-up requests.'}},
    {id:'roofing',business:'Roofing',industry:'home-field-services',role:'Virtual Project Estimating Desk',icon:'roofing',verticalId:'roofing',keywords:['roofer','roof','roof leak','shingles','contractor','estimate'],cardData:{pain:'Storm-related estimate calls flooding the office?',fix:'The Virtual Project Estimating Desk captures roof issues, property details, urgency, and estimate requests.'}},

    {id:'occupational-therapy',business:'Occupational Therapy',industry:'healthcare-wellness',role:'Virtual Appointment Desk',icon:'accessibility_new',keywords:['occupational therapist','therapy','rehabilitation','rehab','pediatric therapy','ot'],cardData:{pain:'Appointment calls arriving while clinicians are with patients?',fix:'The Virtual Appointment Desk captures visit requests, contact details, and preferred scheduling windows.'}},
    {id:'physical-therapy',business:'Physical Therapy',industry:'healthcare-wellness',role:'Virtual Patient Scheduling Desk',icon:'physical_therapy',keywords:['physical therapist','physio','physiotherapy','rehab','injury','mobility','pt'],cardData:{pain:'The front desk balancing check-ins and new-patient calls?',fix:'The Virtual Patient Scheduling Desk captures appointment requests and a clear practice follow-up path.'}},
    {id:'spas',business:'Spas',industry:'healthcare-wellness',role:'Virtual Spa Concierge',icon:'spa',keywords:['spa','massage','facial','wellness','esthetician','med spa'],cardData:{pain:'Treatment-room time interrupted by booking calls?',fix:'The Virtual Spa Concierge captures service interest, scheduling preferences, and guest contact information.'}},
    {id:'small-practices',business:'Small Practices',industry:'healthcare-wellness',role:'Virtual Practice Assistant',icon:'clinical_notes',keywords:['doctor office','medical office','clinic','practice','patients','physician'],cardData:{pain:'A small front desk handling patients and every incoming call?',fix:'The Virtual Practice Assistant captures routine inquiries, appointment needs, and follow-up information.'}},
    {id:'urgent-care',business:'Urgent Care',industry:'healthcare-wellness',role:'Virtual Triage & Intake Desk',icon:'emergency',keywords:['walk in clinic','medical','clinic','patient','same day care','urgent'],cardData:{pain:'Walk-in volume and incoming questions peaking together?',fix:'The Virtual Triage & Intake Desk captures the reason for the call and routes it through a defined intake path.'}},
    {id:'veterinary',business:'Veterinary',industry:'healthcare-wellness',role:'Virtual Clinic Receptionist',icon:'pets',keywords:['vet','animal hospital','pets','dogs','cats','clinic'],cardData:{pain:'Pet owners calling while the clinic team is assisting animals?',fix:'The Virtual Clinic Receptionist captures pet, owner, appointment, and callback details.'}},
    {id:'chiropractors',business:'Chiropractors',industry:'healthcare-wellness',role:'Virtual Patient Coordinator',icon:'health_and_safety',keywords:['chiropractor','chiro','back pain','adjustment','wellness','clinic'],cardData:{pain:'New-patient calls arriving during adjustments?',fix:'The Virtual Patient Coordinator captures appointment interest and prepares a clear follow-up path.'}},
    {id:'dental',business:'Dental Practices',industry:'healthcare-wellness',role:'Virtual Patient Coordinator',icon:'dentistry',keywords:['teeth','dentist','dentists','dental','orthodontist','cleaning','dental office','oral health'],cardData:{pain:'Check-in line backing up while new patients call?',fix:'The Virtual Patient Coordinator captures routine appointment and rescheduling requests for practice follow-up.'}},
    {id:'hearing-audiology',business:'Hearing & Audiology',industry:'healthcare-wellness',role:'Virtual Clinic Assistant',icon:'hearing',keywords:['audiologist','hearing aids','hearing test','ears','audiology','clinic'],cardData:{pain:'Hearing-aid and appointment questions tying up the clinic desk?',fix:'The Virtual Clinic Assistant captures patient questions, appointment needs, and callback details.'}},
    {id:'mental-health-counseling',business:'Mental Health & Counseling',industry:'healthcare-wellness',role:'Virtual Practice Intake Coordinator',icon:'psychology',keywords:['therapist','counselor','counseling','behavioral health','psychologist','therapy'],cardData:{pain:'Sensitive intake calls arriving while clinicians are in sessions?',fix:'The Virtual Practice Intake Coordinator captures contact and appointment requests through a defined intake path.'}},
    {id:'speech-therapy',business:'Speech Therapy',industry:'healthcare-wellness',role:'Virtual Clinic Coordinator',icon:'record_voice_over',keywords:['speech therapist','slp','speech pathology','language therapy','clinic','therapy'],cardData:{pain:'Family scheduling calls competing with therapy sessions?',fix:'The Virtual Clinic Coordinator captures scheduling needs, contact information, and follow-up requests.'}},

    {id:'event-venues',business:'Event Venues',industry:'hospitality-retail',role:'Virtual Booking Concierge',icon:'celebration',keywords:['wedding','banquet','hall','venue','events','party','reception'],cardData:{pain:'Tour and date-availability calls arriving during live events?',fix:'The Virtual Booking Concierge captures event type, date, guest count, and tour requests.'}},
    {id:'high-end-salons',business:'High-End Salons',industry:'hospitality-retail',role:'Virtual Salon Coordinator',icon:'content_cut',keywords:['salon','hair','stylist','beauty','barber','color','appointment'],cardData:{pain:'Stylists working with clients while appointment calls ring?',fix:'The Virtual Salon Coordinator captures service interest, stylist preferences, and scheduling requests.'}},
    {id:'hotels',business:'Hotels & Motels',industry:'hospitality-retail',role:'Virtual Guest Services Desk',icon:'hotel',verticalId:'hotels',keywords:['hotel','motel','lodging','rooms','reservations','guest','hospitality'],cardData:{pain:'Reservation calls arriving during the check-in rush?',fix:'The Virtual Guest Services Desk captures reservation and guest-service requests for front-desk follow-up.'}},
    {id:'boutiques',business:'Boutiques',industry:'hospitality-retail',role:'Virtual Storefront Associate',icon:'storefront',keywords:['boutique','clothing','fashion','retail','shop','store'],cardData:{pain:'Customer questions arriving while staff help shoppers in person?',fix:'The Virtual Storefront Associate captures product, availability, order, and callback questions.'}},
    {id:'florists',business:'Florists',industry:'hospitality-retail',role:'Virtual Order & Floral Desk',icon:'local_florist',keywords:['florist','flowers','bouquet','wedding flowers','delivery','flower shop'],cardData:{pain:'Order calls peaking while designers prepare arrangements?',fix:'The Virtual Order & Floral Desk captures occasion, arrangement, delivery, and contact details.'}},
    {id:'music-instrument-retail',business:'Music & Instrument Retail',industry:'hospitality-retail',role:'Virtual Storefront Coordinator',icon:'music_note',keywords:['music store','guitar','instrument','piano','band','retail'],cardData:{pain:'Instrument questions arriving while staff assist customers?',fix:'The Virtual Storefront Coordinator captures product interest, service needs, and follow-up information.'}},
    {id:'print-shops',business:'Print Shops',industry:'hospitality-retail',role:'Virtual Order & Print Desk',icon:'print',keywords:['printer','printing','copies','signage','banners','print'],cardData:{pain:'Quote and status calls interrupting production work?',fix:'The Virtual Order & Print Desk captures project type, quantity, timing, and order questions.'}},
    {id:'restaurants',business:'Restaurants',industry:'hospitality-retail',role:'Virtual Digital Order Desk',icon:'restaurant',verticalId:'restaurants',keywords:['restaurant','food','takeout','reservation','dining','orders','cafe'],cardData:{pain:'Calls stacking up during the lunch or dinner rush?',fix:'The Virtual Digital Order Desk captures reservation, order, and guest-service requests.'}},

    {id:'real-estate',business:'Real Estate',industry:'professional-services',role:'Virtual Showing Coordinator',icon:'real_estate_agent',keywords:['realtor','realty','agent','broker','homes','showing','property sales'],cardData:{pain:'Showing inquiries arriving while agents are with clients?',fix:'The Virtual Showing Coordinator captures property interest, availability, and preferred showing times.'}},
    {id:'law-firms',business:'Law Firms',industry:'professional-services',role:'Virtual Legal Intake Coordinator',icon:'balance',keywords:['attorney','lawyer','legal','practice','court','firm','case'],cardData:{pain:'Intake calls hitting voicemail while the team is in court?',fix:'The Virtual Legal Intake Coordinator captures the reason for the inquiry and a defined attorney follow-up path.'}},
    {id:'sign-shops',business:'Sign Shops',industry:'professional-services',role:'Virtual Project Intake Desk',icon:'signpost',keywords:['signage','sign maker','banners','graphics','wraps','printing'],cardData:{pain:'Project calls interrupting design and production work?',fix:'The Virtual Project Intake Desk captures sign type, dimensions, timing, and estimate requests.'}},
    {id:'accounting',business:'Accounting',industry:'professional-services',role:'Virtual Office Administrator',icon:'calculate',verticalId:'accounting',keywords:['accountant','bookkeeper','tax','cpa','payroll','finance','office'],cardData:{pain:'Client calls peaking during tax and payroll deadlines?',fix:'The Virtual Office Administrator captures service needs, document questions, and callback requests.'}},
    {id:'insurance-agencies',business:'Insurance Agencies',industry:'professional-services',role:'Virtual Account Associate',icon:'shield',keywords:['insurance agent','policy','claims','coverage','broker','quote'],cardData:{pain:'Quote and policy calls competing for the same account team?',fix:'The Virtual Account Associate captures the policy question, coverage need, and contact information.'}},

    {id:'facilities-management',business:'Facilities Management',industry:'industrial-logistics',role:'Virtual Maintenance Dispatcher',icon:'business',keywords:['facility','facilities','maintenance','building','work orders','janitorial','operations'],cardData:{pain:'Maintenance requests arriving from multiple buildings at once?',fix:'The Virtual Maintenance Dispatcher captures site, issue, urgency, and requester information.'}},
    {id:'logistics-3pl',business:'Logistics & 3PL',industry:'industrial-logistics',role:'Virtual Logistics Dispatcher',icon:'local_shipping',keywords:['shipping','freight','transportation','supply chain','dispatch','delivery','logistics'],cardData:{pain:'Shipment-status calls interrupting active dispatch work?',fix:'The Virtual Logistics Dispatcher captures shipment, location, timing, and callback details.'}},
    {id:'manufacturing',business:'Manufacturing',industry:'industrial-logistics',role:'Virtual Operations Desk',icon:'factory',keywords:['factory','plant','production','manufacturer','operations','supplier'],cardData:{pain:'Supplier and customer calls bouncing between departments?',fix:'The Virtual Operations Desk captures the operational request and routes a clear follow-up handoff.'}},
    {id:'warehouses',business:'Warehouses',industry:'industrial-logistics',role:'Virtual Receiving Coordinator',icon:'warehouse',keywords:['warehouse','receiving','inventory','distribution','dock','shipment'],cardData:{pain:'Dock and receiving calls arriving while crews unload freight?',fix:'The Virtual Receiving Coordinator captures shipment, carrier, dock, timing, and contact details.'}},

    {id:'public-works-utilities',business:'Public Works & Utilities',industry:'property-government',role:'Virtual Utility Dispatcher',icon:'water_drop',keywords:['utilities','utility','water department','roads','sanitation','public works'],cardData:{pain:'Resident service reports arriving across multiple departments?',fix:'The Virtual Utility Dispatcher captures location, service issue, urgency, and resident contact information.'}},
    {id:'apartment-communities',business:'Apartment Communities',industry:'property-government',role:'Virtual Leasing Desk',icon:'apartment',keywords:['apartment','apartments','leasing','rental','rent','property','tenant','resident'],cardData:{pain:'Leasing calls arriving while the team is touring prospects?',fix:'The Virtual Leasing Desk captures floor-plan interest, move-in timing, and tour requests.'}},
    {id:'commercial-property-management',business:'Commercial Property Management',industry:'property-government',role:'Virtual Tenant Services Coordinator',icon:'domain',keywords:['property manager','commercial building','tenant','maintenance','lease','facility'],cardData:{pain:'Tenant requests scattered across properties and teams?',fix:'The Virtual Tenant Services Coordinator captures property, suite, request, and urgency details.'}},
    {id:'hoa-condo-associations',business:'HOA & Condo Associations',industry:'property-government',role:'Virtual Association Liaison',icon:'location_city',keywords:['hoa','condo','homeowners association','community association','resident','board'],cardData:{pain:'Resident questions overwhelming a small association office?',fix:'The Virtual Association Liaison captures the property, question, and appropriate board or management follow-up.'}},
    {id:'municipal-city-government',business:'Municipal & City Government',industry:'property-government',role:'Virtual Citizen Services Desk',icon:'account_balance',keywords:['city hall','municipality','government','citizen','permits','public services'],cardData:{pain:'Citizens unsure which department handles their request?',fix:'The Virtual Citizen Services Desk captures the service need and routes a clear departmental handoff.'}},

    {id:'daycares',business:'Daycares',industry:'education-community',role:'Virtual Center Coordinator',icon:'child_care',keywords:['daycare','childcare','preschool','parents','enrollment','children'],cardData:{pain:'Parent and enrollment calls arriving during classroom transitions?',fix:'The Virtual Center Coordinator captures enrollment interest, child details, and tour requests.'}},
    {id:'charter-schools',business:'Charter Schools',industry:'education-community',role:'Virtual Enrollment & Info Desk',icon:'school',keywords:['charter school','school','students','enrollment','education','academy'],cardData:{pain:'Enrollment questions peaking while the office supports students?',fix:'The Virtual Enrollment & Info Desk captures family questions, grade level, and follow-up details.'}},
    {id:'churches',business:'Churches',industry:'education-community',role:'Virtual Ministry Coordinator',icon:'church',keywords:['church','ministry','pastor','congregation','worship','parish'],cardData:{pain:'Member and visitor calls arriving while staff lead programs?',fix:'The Virtual Ministry Coordinator captures ministry, event, assistance, and follow-up requests.'}},
    {id:'nonprofits',business:'Nonprofits',industry:'education-community',role:'Virtual Community Outreach Desk',icon:'volunteer_activism',keywords:['nonprofit','charity','donor','volunteer','community','foundation'],cardData:{pain:'Program, donor, and volunteer calls competing for a small team?',fix:'The Virtual Community Outreach Desk captures the reason for contact and the appropriate program handoff.'}},
    {id:'private-religious-schools',business:'Private & Religious Schools',industry:'education-community',role:'Virtual Admissions Assistant',icon:'menu_book',keywords:['private school','religious school','admissions','students','enrollment','academy'],cardData:{pain:'Admissions calls arriving during the school-day office rush?',fix:'The Virtual Admissions Assistant captures grade, enrollment timing, tour, and family contact details.'}}
  ];
})();
